version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: geosense-db
    environment:
      POSTGRES_DB: geoai
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geo -d geoai"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: geosense-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geosense-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Override DB/Redis to point to internal service hosts
      DATABASE_URL: postgresql://geo:geo123!@db:5432/geoai
      REDIS_URL: redis://redis:6379
      DEBUG: "false"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./frontend:/app/frontend
      - ./trips.csv:/app/trips.csv:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
